# Generated by Django 4.2.4 on 2023-10-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albumes', '0004_alter_blogpost_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
