# Generated by Django 4.2.4 on 2023-10-06 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albumes', '0005_delete_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='usuario',
        ),
    ]
